/**
 * PptxGenJS 插件 - 前端封装
 * 与原生代码隔离的 PPT 生成插件
 */

import PptxGenJS from 'pptxgenjs'

class PptxGenerator {
  constructor(options = {}) {
    this.pptx = null
    this.options = {
      title: options.title || 'PPT 演示文稿',
      author: options.author || 'Generated by AI',
      subject: options.subject || '',
      layout: options.layout || 'LAYOUT_16x9',
      ...options
    }
  }

  init() {
    this.pptx = new PptxGenJS()
    this.pptx.author = this.options.author
    this.pptx.title = this.options.title
    this.pptx.subject = this.options.subject
    this.pptx.layout = this.options.layout
    return this
  }

  /**
   * 添加标题页
   */
  addTitleSlide(title, subtitle = '') {
    if (!this.pptx) this.init()
    
    this.pptx.addSlide()
      .addText(title, {
        x: 0.5,
        y: 2.0,
        w: '90%',
        h: 1.5,
        fontSize: 44,
        bold: true,
        color: '363636',
        align: 'center',
        valign: 'middle'
      })

    if (subtitle) {
      this.pptx.slide.addText(subtitle, {
        x: 0.5,
        y: 3.8,
        w: '90%',
        h: 0.8,
        fontSize: 24,
        color: '666666',
        align: 'center',
        valign: 'middle'
      })
    }
    return this
  }

  /**
   * 添加内容页
   */
  addContentSlide(title, points = []) {
    if (!this.pptx) this.init()

    const slide = this.pptx.addSlide()
    slide.background = { color: 'FFFFFF' }

    // 标题栏
    slide.addShape(this.pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: '100%',
      h: 1.0,
      fill: { color: '2B579A' }
    })

    slide.addText(title, {
      x: 0.5,
      y: 0.2,
      w: '90%',
      h: 0.6,
      fontSize: 28,
      bold: true,
      color: 'FFFFFF',
      margin: 0
    })

    // 内容要点
    if (points && points.length > 0) {
      const bulletPoints = points.map((point, index) => ({
        text: point,
        options: { bullet: true, breakLine: index < points.length - 1 }
      }))

      slide.addText(bulletPoints, {
        x: 0.8,
        y: 1.4,
        w: '85%',
        h: 4.0,
        fontSize: 18,
        color: '363636',
        paraSpaceAfter: 12,
        valign: 'top'
      })
    }
    return this
  }

  /**
   * 添加分节页
   */
  addSectionSlide(title) {
    if (!this.pptx) this.init()

    this.pptx.addSlide()
      .addShape(this.pptx.ShapeType.rect, {
        x: 0,
        y: 2.0,
        w: '100%',
        h: 1.5,
        fill: { color: '2B579A' }
      })
      .addText(title, {
        x: 0.5,
        y: 2.2,
        w: '90%',
        h: 1.0,
        fontSize: 36,
        bold: true,
        color: 'FFFFFF',
        align: 'center',
        valign: 'middle'
      })
    return this
  }

  /**
   * 添加总结页
   */
  addSummarySlide(points = []) {
    if (!this.pptx) this.init()

    const slide = this.pptx.addSlide()
    slide.background = { color: 'F5F5F5' }

    slide.addText('总结', {
      x: 0.5,
      y: 0.5,
      w: '90%',
      h: 0.8,
      fontSize: 32,
      bold: true,
      color: '2B579A',
      align: 'center'
    })

    if (points && points.length > 0) {
      slide.addText(
        points.map((point, i) => ({
          text: point,
          options: { bullet: true, breakLine: i < points.length - 1 }
        })),
        {
          x: 1.0,
          y: 1.6,
          w: '80%',
          h: 3.5,
          fontSize: 18,
          color: '363636',
          paraSpaceAfter: 10
        }
      )
    }
    return this
  }

  /**
   * 导出为 Blob
   */
  async exportAsBlob() {
    if (!this.pptx) {
      throw new Error('PPT 未初始化，请先添加幻灯片')
    }
    return await this.pptx.write({ outputType: 'blob' })
  }

  /**
   * 导出为 Base64
   */
  async exportAsBase64() {
    if (!this.pptx) {
      throw new Error('PPT 未初始化，请先添加幻灯片')
    }
    return await this.pptx.write({ outputType: 'base64' })
  }

  /**
   * 导出并下载
   */
  async download(filename = 'presentation.pptx') {
    const blob = await this.exportAsBlob()
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = filename
    link.click()
    URL.revokeObjectURL(url)
    return true
  }
}

/**
 * 解析 Markdown 格式的大纲并生成 PPT
 * @param {string} markdownContent - Markdown 格式的大纲
 * @param {object} options - 配置选项
 */
async function createPptFromMarkdown(markdownContent, options = {}) {
  const generator = new PptxGenerator({
    title: options.title || 'PPT 演示文稿',
    author: options.author || 'Generated by AI',
    ...options
  })
  generator.init()

  // 解析 Markdown
  const lines = markdownContent.split('\n')
  let currentSlide = null
  let currentPoints = []

  for (const line of lines) {
    const trimmed = line.trim()
    
    if (trimmed.startsWith('## 第') && trimmed.includes('页：')) {
      // 保存上一页
      if (currentSlide) {
        generator.addContentSlide(currentSlide, currentPoints)
      }
      // 提取标题
      const match = trimmed.match(/## 第\d+页：(.+)/)
      currentSlide = match ? match[1] : '未命名'
      currentPoints = []
    } else if (trimmed.startsWith('## 总结') || trimmed.startsWith('## 总结')) {
      if (currentSlide) {
        generator.addContentSlide(currentSlide, currentPoints)
      }
      generator.addSummarySlide()
      currentSlide = null
      currentPoints = []
    } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      currentPoints.push(trimmed.substring(2))
    } else if (/^\d+\./.test(trimmed)) {
      currentPoints.push(trimmed.replace(/^\d+\.\s*/, ''))
    }
  }

  // 保存最后一页
  if (currentSlide) {
    generator.addContentSlide(currentSlide, currentPoints)
  }

  if (options.autoDownload !== false) {
    await generator.download(options.filename || `${options.title || 'presentation'}.pptx`)
  }

  return generator
}

export { PptxGenerator, createPptFromMarkdown }
export default PptxGenerator
