/**
 * PptxGenJS 插件 - 后端封装
 * 与原生代码隔离的 PPT 生成插件（Node.js 环境）
 */

import PptxGenJS from 'pptxgenjs'
import { writeFile, mkdir } from 'fs/promises'
import { existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

class ServerPptxGenerator {
  constructor(options = {}) {
    this.pptx = null
    this.options = {
      title: options.title || 'PPT 演示文稿',
      author: options.author || 'Generated by AI',
      subject: options.subject || '',
      layout: options.layout || 'LAYOUT_16x9',
      ...options
    }
    this.slides = []
  }

  init() {
    this.pptx = new PptxGenJS()
    this.pptx.author = this.options.author
    this.pptx.title = this.options.title
    this.pptx.subject = this.options.subject
    this.pptx.layout = this.options.layout
    return this
  }

  addTitleSlide(title, subtitle = '') {
    if (!this.pptx) this.init()
    
    this.pptx.addSlide()
      .addText(title, {
        x: 0.5,
        y: 2.0,
        w: '90%',
        h: 1.5,
        fontSize: 44,
        bold: true,
        color: '363636',
        align: 'center',
        valign: 'middle'
      })

    if (subtitle) {
      this.pptx.slide.addText(subtitle, {
        x: 0.5,
        y: 3.8,
        w: '90%',
        h: 0.8,
        fontSize: 24,
        color: '666666',
        align: 'center',
        valign: 'middle'
      })
    }
    return this
  }

  addContentSlide(title, points = []) {
    if (!this.pptx) this.init()

    const slide = this.pptx.addSlide()
    slide.background = { color: 'FFFFFF' }

    slide.addShape(this.pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: '100%',
      h: 1.0,
      fill: { color: '2B579A' }
    })

    slide.addText(title, {
      x: 0.5,
      y: 0.2,
      w: '90%',
      h: 0.6,
      fontSize: 28,
      bold: true,
      color: 'FFFFFF',
      margin: 0
    })

    if (points && points.length > 0) {
      const bulletPoints = points.map((point, index) => ({
        text: point,
        options: { bullet: true, breakLine: index < points.length - 1 }
      }))

      slide.addText(bulletPoints, {
        x: 0.8,
        y: 1.4,
        w: '85%',
        h: 4.0,
        fontSize: 18,
        color: '363636',
        paraSpaceAfter: 12,
        valign: 'top'
      })
    }
    return this
  }

  addSectionSlide(title) {
    if (!this.pptx) this.init()

    this.pptx.addSlide()
      .addShape(this.pptx.ShapeType.rect, {
        x: 0,
        y: 2.0,
        w: '100%',
        h: 1.5,
        fill: { color: '2B579A' }
      })
      .addText(title, {
        x: 0.5,
        y: 2.2,
        w: '90%',
        h: 1.0,
        fontSize: 36,
        bold: true,
        color: 'FFFFFF',
        align: 'center',
        valign: 'middle'
      })
    return this
  }

  addSummarySlide(points = []) {
    if (!this.pptx) this.init()

    const slide = this.pptx.addSlide()
    slide.background = { color: 'F5F5F5' }

    slide.addText('总结', {
      x: 0.5,
      y: 0.5,
      w: '90%',
      h: 0.8,
      fontSize: 32,
      bold: true,
      color: '2B579A',
      align: 'center'
    })

    if (points && points.length > 0) {
      slide.addText(
        points.map((point, i) => ({
          text: point,
          options: { bullet: true, breakLine: i < points.length - 1 }
        })),
        {
          x: 1.0,
          y: 1.6,
          w: '80%',
          h: 3.5,
          fontSize: 18,
          color: '363636',
          paraSpaceAfter: 10
        }
      )
    }
    return this
  }

  async exportAsBuffer() {
    if (!this.pptx) {
      throw new Error('PPT 未初始化，请先添加幻灯片')
    }
    return await this.pptx.write({ outputType: 'nodebuffer' })
  }

  async saveToFile(filepath) {
    const buffer = await this.exportAsBuffer()
    const dir = dirname(filepath)
    
    if (!existsSync(dir)) {
      await mkdir(dir, { recursive: true })
    }
    
    await writeFile(filepath, buffer)
    return filepath
  }
}

/**
 * 解析 Markdown 格式的大纲并生成 PPT
 * @param {string} markdownContent - Markdown 格式的大纲
 * @param {object} options - 配置选项
 */
async function createPptFromMarkdown(markdownContent, options = {}) {
  const generator = new ServerPptxGenerator({
    title: options.title || 'PPT 演示文稿',
    author: options.author || 'Generated by AI',
    ...options
  })
  generator.init()

  const lines = markdownContent.split('\n')
  let currentSlide = null
  let currentPoints = []

  for (const line of lines) {
    const trimmed = line.trim()
    
    if (trimmed.startsWith('## 第') && trimmed.includes('页：')) {
      if (currentSlide) {
        generator.addContentSlide(currentSlide, currentPoints)
      }
      const match = trimmed.match(/## 第\d+页：(.+)/)
      currentSlide = match ? match[1] : '未命名'
      currentPoints = []
    } else if (trimmed.startsWith('## 总结') || trimmed.startsWith('## 总结')) {
      if (currentSlide) {
        generator.addContentSlide(currentSlide, currentPoints)
      }
      generator.addSummarySlide()
      currentSlide = null
      currentPoints = []
    } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      currentPoints.push(trimmed.substring(2))
    } else if (/^\d+\./.test(trimmed)) {
      currentPoints.push(trimmed.replace(/^\d+\.\s*/, ''))
    }
  }

  if (currentSlide) {
    generator.addContentSlide(currentSlide, currentPoints)
  }

  if (options.outputPath) {
    await generator.saveToFile(options.outputPath)
    return { success: true, path: options.outputPath }
  }

  const buffer = await generator.exportAsBuffer()
  return { success: true, buffer }
}

/**
 * 插件 API 路由注册函数
 * @param {Express} app - Express 应用实例
 */
function registerPptxPluginRoutes(app) {
  // 生成 PPT
  app.post('/api/plugins/pptx/generate', async (req, res) => {
    try {
      const { content, title, author, outputDir } = req.body

      if (!content) {
        return res.status(400).json({ 
          success: false, 
          error: '缺少内容参数' 
        })
      }

      const filename = `${Date.now()}_${(title || 'presentation').replace(/[^a-zA-Z0-9\u4e00-\u9fa5]/g, '_')}.pptx`
      const outputPath = outputDir 
        ? join(outputDir, filename)
        : join(process.cwd(), 'uploads', 'ppt', filename)

      const result = await createPptFromMarkdown(content, {
        title: title || 'PPT 演示文稿',
        author: author || 'Generated by AI',
        outputPath
      })

      res.json({
        success: true,
        data: {
          filename,
          path: `/uploads/ppt/${filename}`,
          size: result.buffer?.length || 0
        }
      })
    } catch (error) {
      console.error('PPT 生成失败:', error)
      res.status(500).json({ 
        success: false, 
        error: 'PPT 生成失败: ' + error.message 
      })
    }
  })

  // 下载已生成的 PPT
  app.get('/api/plugins/pptx/download/:filename', async (req, res) => {
    try {
      const { filename } = req.params
      const filepath = join(process.cwd(), 'uploads', 'ppt', filename)

      if (!existsSync(filepath)) {
        return res.status(404).json({ 
          success: false, 
          error: '文件不存在' 
        })
      }

      res.download(filepath)
    } catch (error) {
      console.error('下载失败:', error)
      res.status(500).json({ 
        success: false, 
        error: '下载失败' 
      })
    }
  })

  console.log('✅ PptxGenJS 插件已加载')
}

export { ServerPptxGenerator, createPptFromMarkdown, registerPptxPluginRoutes }
export default ServerPptxGenerator
